environment:
  matrix:
#    - nodejs_version: "6"
#    - nodejs_version: "7"
    - nodejs_version: ""

init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install -g yo
  - npm install
  - npm link

test_script:
  - node --version
  - npm --version
  - bash
  - npm test

build: off

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

