name: release
on:
  workflow_dispatch:
  repository_dispatch:
    types: [release]

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - run: git config --global core.autocrlf false
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install dependencies
        run: |
          npm ci
          npm link
        env:
          CI: true
      - run: npx semantic-release
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          # Need owner/admin account to bypass branch protection
          GIT_COMMITTER_NAME: ci-rebot
          GIT_COMMITTER_EMAIL: cirebot.github@gmail.com
      - name: Configure git
        run: |
          git config --global user.email "ci-rebot"
          git config --global user.name "cirebot.github@gmail.com"
      - name: Deploy starter-kit updates
        run: npm run deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
